# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Telefono', models.CharField(max_length=200)),
                ('Direccion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='img')),
            ],
        ),
    ]
